- name: reconfigure gitlab
  command: gitlab-ctl reconfigure

- name: restart gitlab
  command: gitlab-ctl restart

- name: upgrade gitlab
  command: gitlab-ctl upgrade

- name: restart gitlab nginx
  command: gitlab-ctl restart nginx

- name: start gitlab
  command: gitlab-ctl start

- name: wait for unicorn
  wait_for:
    port: 8080
